name: CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle wrapper
        run: ./gradlew build
